//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataTypeAttribute(typeof(BeatDetailMeta))]
    public partial class BeatDetail
    {
        
    }


    public class BeatDetailMeta
    {
        //public BeatDetail()
        //{
        //    this.OrderDetails = new HashSet<OrderDetail>();
        //    this.RetailerDetails = new HashSet<RetailerDetail>();
        //    this.BeatDistributorMappings = new HashSet<BeatDistributorMapping>();
        //    this.RetailBeatMappings = new HashSet<RetailBeatMapping>();
        //}
    
        public int ID { get; set; }

        [Required]
        public string Code { get; set; }
        public string Name { get; set; }

        [Display(Name = "Distributor")]
        public Nullable<int> Distributor_Id { get; set; }

        [Display(Name = "Contact person")]
        public string Contact_person { get; set; }
        public string State { get; set; }

        [Display(Name = "City")]
        public string Cityarea { get; set; }
        public string Address { get; set; }

        [Display(Name = "Pin Code")]
        public string Pin_Code { get; set; }

        [Display(Name = "Contact Number")]
        public string Contact_Number { get; set; }

        [Display(Name = "Active")]
        public Nullable<bool> Active_Status { get; set; }

         [Display(Name = "Date Of Joining")]
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
    
        //public virtual DistDealerDetail DistDealerDetail { get; set; }
        //public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        //public virtual ICollection<RetailerDetail> RetailerDetails { get; set; }
        //public virtual ICollection<BeatDistributorMapping> BeatDistributorMappings { get; set; }
        //public virtual ICollection<RetailBeatMapping> RetailBeatMappings { get; set; }
    }
}
