//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuminousBikerAppEntities : DbContext
    {
        public LuminousBikerAppEntities()
            : base("name=LuminousBikerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BeatDetail> BeatDetails { get; set; }
        public DbSet<BikerBoyDetail> BikerBoyDetails { get; set; }
        public DbSet<BikerDistMapping> BikerDistMappings { get; set; }
        public DbSet<DistDealerDetail> DistDealerDetails { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<RetailerDetail> RetailerDetails { get; set; }
        public DbSet<Logger> Loggers { get; set; }
        public DbSet<BeatDistributorMapping> BeatDistributorMappings { get; set; }
        public DbSet<RetailBeatMapping> RetailBeatMappings { get; set; }
        public DbSet<MHrOtp> MHrOtps { get; set; }
    }
}
