//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataTypeAttribute(typeof(DistDealerDetailMeta))]
    public partial class DistDealerDetail
    {
        
    }

    public class DistDealerDetailMeta
    {
        //public DistDealerDetail()
        //{
        //    this.BeatDetails = new HashSet<BeatDetail>();
        //    this.BikerDistMappings = new HashSet<BikerDistMapping>();
        //    this.OrderDetails = new HashSet<OrderDetail>();
        //    this.BeatDistributorMappings = new HashSet<BeatDistributorMapping>();
        //}
    
        public int ID { get; set; }

        [Display(Name = "Customer Type")]
        public string Customer_Type { get; set; }

        [Display(Name = "Code")]
        [Required]
        public string Dis_Sap_Code { get; set; }

        [Display(Name = "Name")]
        public string Dis_Name { get; set; }

        [Display(Name = "Address1")]
        public string Dis_Address1 { get; set; }

        [Display(Name = "Address2")]
        public string Dis_Address2 { get; set; }

        [Display(Name = "City")]
        public string Dis_City { get; set; }

        [Display(Name = "District")]
        public string Dis_District { get; set; }

        [Display(Name = "State")]
        public string Dis_State { get; set; }

        [Display(Name = "Contact Number")]
        public string Dis_ContactNo { get; set; }

        [Display(Name = "Email")]
        public string Dis_Email { get; set; }

        [Display(Name = "Region Code")]
        public string Region_code { get; set; }

        [Display(Name = "Active")]
        public Nullable<bool> isActive { get; set; }

        [Display(Name = "Activated By")]
        public string ActivatedBY { get; set; }

        [Display(Name = "Activated Date")]
        public Nullable<System.DateTime> ActivatedDate { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> Created_On { get; set; }

        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> Updated_On { get; set; }

        [Display(Name = "Blocked By")]
        public string Blocked_By { get; set; }

        [Display(Name = "Blocked Date")]
        public Nullable<System.DateTime> Blocked_Date { get; set; }
    
        //public virtual ICollection<BeatDetail> BeatDetails { get; set; }
        //public virtual ICollection<BikerDistMapping> BikerDistMappings { get; set; }
        //public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        //public virtual ICollection<BeatDistributorMapping> BeatDistributorMappings { get; set; }
    }
}
