//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ID { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<double> Required_Quantity { get; set; }
        public Nullable<double> Supplied_Quantity { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Updated_By { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
