//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Of_Visit { get; set; }
        public Nullable<int> Distributor_Id { get; set; }
        public Nullable<int> Beat_Id { get; set; }
        public Nullable<int> Retailer_Id { get; set; }
        public Nullable<bool> Visted { get; set; }
        public Nullable<bool> Sold { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Ordered_On { get; set; }
        public string Order_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Updated_By { get; set; }
    
        public virtual BeatDetail BeatDetail { get; set; }
        public virtual DistDealerDetail DistDealerDetail { get; set; }
        public virtual RetailerDetail RetailerDetail { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
