<?xml version="1.0" encoding="utf-8"?><Database Name="LuminousBikerApp" Class="BikerDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IP-50-62-56-149;Initial Catalog=LuminousBikerApp;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="LuminousBikerAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BikerDistMapping" Member="BikerDistMappings">
    <Type Name="BikerDistMapping">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Distributor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BikerBoy_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BikerBoyDetail_BikerDistMapping" Member="BikerBoyDetail" ThisKey="BikerBoy_Id" OtherKey="ID" Type="BikerBoyDetail" IsForeignKey="true" />
      <Association Name="DistDealerDetail_BikerDistMapping" Member="DistDealerDetail" ThisKey="Distributor_Id" OtherKey="ID" Type="DistDealerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Item_OrderItem" Member="OrderItems" ThisKey="ID" OtherKey="Item_Id" Type="OrderItem" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date_Of_Visit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Distributor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Beat_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Retailer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ordered_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Order_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="OrderDetail_OrderItem" Member="OrderItems" ThisKey="ID" OtherKey="Order_Id" Type="OrderItem" />
      <Association Name="BeatDetail_OrderDetail" Member="BeatDetail" ThisKey="Beat_Id" OtherKey="ID" Type="BeatDetail" IsForeignKey="true" />
      <Association Name="RetailerDetail_OrderDetail" Member="RetailerDetail" ThisKey="Retailer_Id" OtherKey="ID" Type="RetailerDetail" IsForeignKey="true" />
      <Association Name="DistDealerDetail_OrderDetail" Member="DistDealerDetail" ThisKey="Distributor_Id" OtherKey="ID" Type="DistDealerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Order_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Item_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Required_Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Supplied_Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Item_OrderItem" Member="Item" ThisKey="Item_Id" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="OrderDetail_OrderItem" Member="OrderDetail" ThisKey="Order_Id" OtherKey="ID" Type="OrderDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MHrOtp" Member="MHrOtps">
    <Type Name="MHrOtp">
      <Column Name="seqid" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="empid" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="imeinumber" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="osversion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="devicename" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="otpstatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="varifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="expireon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appversion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="appid" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="devid" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ostype" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BeatDetail" Member="BeatDetails">
    <Type Name="BeatDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_person" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cityarea" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Pin_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Active_Status" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Date_Of_Joining" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BeatDetail_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="Beat_Id" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.RetailerDetail" Member="RetailerDetails">
    <Type Name="RetailerDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_person" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CityArea" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Pin_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Active_Status" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Date_Of_Joining" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="RetailerDetail_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="Retailer_Id" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.BikerBoyDetail" Member="BikerBoyDetails">
    <Type Name="BikerBoyDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BB_Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BB_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Of_Joining" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Zonal_Code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BB_State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mob" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ZM_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZM_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RM_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RM_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ASM_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ASM_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Cord1_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cord1_Code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cord2_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cord2_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Active" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BranchManager" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="BikerBoyDetail_BikerDistMapping" Member="BikerDistMappings" ThisKey="ID" OtherKey="BikerBoy_Id" Type="BikerDistMapping" />
    </Type>
  </Table>
  <Table Name="dbo.DistDealerDetail" Member="DistDealerDetails">
    <Type Name="DistDealerDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_Type" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Sap_Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Address1" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Dis_Address2" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Dis_City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Dis_District" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Dis_State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Dis_ContactNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Region_code" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="isActive" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ActivatedBY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ActivatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Blocked_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Blocked_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DistDealerDetail_BikerDistMapping" Member="BikerDistMappings" ThisKey="ID" OtherKey="Distributor_Id" Type="BikerDistMapping" />
      <Association Name="DistDealerDetail_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="Distributor_Id" Type="OrderDetail" />
    </Type>
  </Table>
  <Function Name="dbo.SP_GetItems" Method="SP_GetItems">
    <ElementType Name="SP_GetItemsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OrderDetails_By_Id" Method="SP_OrderDetails_By_Id">
    <Parameter Name="orderid" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_OrderDetails_By_IdResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date_Of_Visit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Distributor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Beat_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Retailer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ordered_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Order_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetOrders_By_DistId_RetailerId_BeatId_BikerId" Method="SP_GetOrders_By_DistId_RetailerId_BeatId_BikerId">
    <Parameter Name="destributorid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="RetailerId" Parameter="retailerId" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="beatid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="bikersloginid" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_GetOrders_By_DistId_RetailerId_BeatId_BikerIdResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date_Of_Visit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Distributor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Beat_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Retailer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ordered_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Order_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_UpateOrder" Method="SP_UpateOrder">
    <Parameter Name="orderid" Type="System.Int32" DbType="Int" />
    <Parameter Name="itemid" Type="System.Int32" DbType="Int" />
    <Parameter Name="suppliedquantity" Type="System.Double" DbType="Float" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_UpateOrderResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MHrCreateOtp" Method="MHrCreateOtp">
    <Parameter Name="empid" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="imeinumber" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="osversion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="devicename" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="appversion" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="MHrCreateOtpResult">
      <Column Name="Biker_Code" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Biker_Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Biker_EmailId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Biker_Mob" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MHrVarifyOtpNotification" Method="MHrVarifyOtpNotification">
    <Parameter Name="empid" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="imeinumber" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="osversion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="devicename" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="otp" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="appid" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="devid" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ostype" Type="System.String" DbType="VarChar(12)" />
    <ElementType Name="MHrVarifyOtpNotificationResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetBeatList_By_DistId_BikerId" Method="SP_GetBeatList_By_DistId_BikerId">
    <Parameter Name="bdistributorid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="bikersloginid" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_GetBeatList_By_DistId_BikerIdResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetDistributors_By_BikersLogInId" Method="SP_GetDistributors_By_BikersLogInId">
    <Parameter Name="bikersloginid" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_GetDistributors_By_BikersLogInIdResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Type" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Sap_Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Dis_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetRetailerList_By_BeatId_DistId_BikerId" Method="SP_GetRetailerList_By_BeatId_DistId_BikerId">
    <Parameter Name="beatid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="bdistributorid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="bikersloginid" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="searchstringretailername" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_GetRetailerList_By_BeatId_DistId_BikerIdResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>