//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeatDistributorMapping
    {
        public int ID { get; set; }
        public int Distributor_Id { get; set; }
        public int Beat_Id { get; set; }
    
        public virtual BeatDetail BeatDetail { get; set; }
        public virtual DistDealerDetail DistDealerDetail { get; set; }
    }
}
