//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikerDistMapping
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_Id { get; set; }
        public Nullable<int> BikerBoy_Id { get; set; }
    
        public virtual BikerBoyDetail BikerBoyDetail { get; set; }
        public virtual DistDealerDetail DistDealerDetail { get; set; }
    }
}
