//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LuminousBikerAppEntities : DbContext
    {
        public LuminousBikerAppEntities()
            : base("name=LuminousBikerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BikerDistMapping> BikerDistMappings { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Logger> Loggers { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BeatDistributorMapping> BeatDistributorMappings { get; set; }
        public virtual DbSet<RetailBeatMapping> RetailBeatMappings { get; set; }
        public virtual DbSet<BeatDetail> BeatDetails { get; set; }
        public virtual DbSet<BikerBoyDetail> BikerBoyDetails { get; set; }
        public virtual DbSet<DistDealerDetail> DistDealerDetails { get; set; }
        public virtual DbSet<RetailerDetail> RetailerDetails { get; set; }
    
        public virtual int sp_SearchDistributore(string searchParameter)
        {
            var searchParameterParameter = searchParameter != null ?
                new ObjectParameter("SearchParameter", searchParameter) :
                new ObjectParameter("SearchParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchDistributore", searchParameterParameter);
        }
    }
}
