//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataTypeAttribute(typeof(BikerDistMappingMeta))]
    public partial class BikerDistMapping
    {
        
    }

    public class BikerDistMappingMeta
    {
        public int ID { get; set; }

        [Display(Name = "Distributor")]
        [Required]
        public Nullable<int> Distributor_Id { get; set; }

        [Display(Name = "Biker Boy")]
        [Required]
        public Nullable<int> BikerBoy_Id { get; set; }
    
        //public virtual BikerBoyDetail BikerBoyDetail { get; set; }
        //public virtual DistDealerDetail DistDealerDetail { get; set; }
    }
}
