//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikerBoyDetail
    {
        public BikerBoyDetail()
        {
            this.BikerDistMappings = new HashSet<BikerDistMapping>();
        }
    
        public int ID { get; set; }
        public string BB_Code { get; set; }
        public string BB_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
        public string Region { get; set; }
        public string Zonal_Code { get; set; }
        public string BB_State { get; set; }
        public string Town { get; set; }
        public string Mob { get; set; }
        public string ZM_Name { get; set; }
        public string ZM_Code { get; set; }
        public string RM_Name { get; set; }
        public string RM_Code { get; set; }
        public string ASM_Name { get; set; }
        public string ASM_Code { get; set; }
        public string Cord1_Name { get; set; }
        public string Cord1_Code { get; set; }
        public string Cord2_Name { get; set; }
        public string Cord2_Code { get; set; }
        public string Active { get; set; }
        public string BranchManager { get; set; }
    
        public virtual ICollection<BikerDistMapping> BikerDistMappings { get; set; }
    }
}
