//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistDealerDetail
    {
        public DistDealerDetail()
        {
            this.BeatDistributorMappings = new HashSet<BeatDistributorMapping>();
            this.BikerDistMappings = new HashSet<BikerDistMapping>();
        }
    
        public int ID { get; set; }
        public string Customer_Type { get; set; }
        public string Dis_Sap_Code { get; set; }
        public string Dis_Name { get; set; }
        public string Dis_Address1 { get; set; }
        public string Dis_Address2 { get; set; }
        public string Dis_City { get; set; }
        public string Dis_District { get; set; }
        public string Dis_State { get; set; }
        public string Dis_ContactNo { get; set; }
        public string Dis_Email { get; set; }
        public string Region_code { get; set; }
        public string isActive { get; set; }
        public string ActivatedBY { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Blocked_By { get; set; }
        public Nullable<System.DateTime> Blocked_Date { get; set; }
    
        public virtual ICollection<BeatDistributorMapping> BeatDistributorMappings { get; set; }
        public virtual ICollection<BikerDistMapping> BikerDistMappings { get; set; }
    }
}
