//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.Biker.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataTypeAttribute(typeof(RetailerDetailMeta))]
    public partial class RetailerDetail
    {
        
    }

    public class RetailerDetailMeta
    {
        //public RetailerDetail()
        //{
        //    this.OrderDetails = new HashSet<OrderDetail>();
        //    this.RetailBeatMappings = new HashSet<RetailBeatMapping>();
        //}
    
        public int ID { get; set; }

        [Required]
        [Display(Name = "Retailer Code")]
        public string Code { get; set; }
        public string Name { get; set; }

        //[Display(Name = "Beat")]
        //public Nullable<int> Beat_Id { get; set; }

        [Display(Name = "Contact person")]
        public string Contact_person { get; set; }
        public string State { get; set; }

        [Display(Name = "City")]
        public string CityArea { get; set; }
        public string Address { get; set; }

        [Display(Name = "Pin Code")]
        public string Pin_Code { get; set; }

        [Display(Name = "Contact Number")]
        public string Contact_Number { get; set; }

        [Display(Name = "Active")]
        public string Active_Status { get; set; }

        [Display(Name = "Date Of Joining")]
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }

    
        //public virtual BeatDetail BeatDetail { get; set; }
        //public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        //public virtual ICollection<RetailBeatMapping> RetailBeatMappings { get; set; }
    }
}
